<?php

/* custom routes generated by CRUD */

Route::get('/', array('as' => 'home', function () {
    return View::make('index');
}));

Route::get('blog', array('as' => 'blog', 'uses' => 'FrontendBlogController@index'));
Route::get('blog/{slug}/tag', 'FrontendBlogController@getBlogTag');
Route::get('blogitem/{slug?}', 'FrontendBlogController@getBlog');
Route::post('blogitem/{blog}/comment', 'FrontendBlogController@storeComment');

//Route::get('{name?}', 'JoshController@showFrontEndView');
# End of frontend views

Route::get('about-us', function() {
	return view('aboutus');
});

Route::get('team', array('as' => 'team', function () {
    return View::make('aboutus');
}));

Route::get('news', function() {
	return view('news');
});

Route::get('news_item', function() {
	return view('news_item');
});

Route::get('contact', function() {
	return view('contact');
});

Route::get('team', function() {
	return view('team');
});