<?php

/* custom routes generated by CRUD */

Route::get('/', array('as' => 'home', function () {
    return View::make('index');
}));

Route::get('blog', array('as' => 'blog', 'uses' => 'FrontendBlogController@index'));
Route::get('blog/{slug}/tag', 'FrontendBlogController@getBlogTag');
Route::get('blogitem/{slug?}', 'FrontendBlogController@getBlog');
Route::post('blogitem/{blog}/comment', 'FrontendBlogController@storeComment');

//Route::get('{name?}', 'JoshController@showFrontEndView');
# End of frontend views

Route::get('about-us', function() {
	return view('aboutus');
});

Route::get('/team', array('as' => 'team', function () {
    return View::make('team');
}));

Route::get('/partners', array('as' => 'partners', function () {
    return View::make('partners');
}));



Route::get('/news_item', function() {
	return view('news_item');
});

Route::get('/contact', function() {
	return view('contact');
});

Route::get('/team', function() {
	return view('team');
});

Route::group(['prefix' => 'admin', 'middleware' => 'SentinelAdmin', 'as' => 'admin.'], function () {
    # Dashboard / Index
    Route::get('/', array('as' => 'dashboard','uses' => 'JoshController@showHome'));

    // GUI Crud Generator
    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');

    # book Management
    Route::group(array('prefix' => 'books'), function () {
        Route::get('/', array('as' => 'books', 'uses' => 'Admin\BooksController@index'));
        Route::get('data',['as' => 'books.data', 'uses' =>'Admin\BooksController@data']);
        Route::get('create', 'Admin\BooksController@create');
        Route::post('create', 'Admin\BooksController@store');
        Route::get('{book}/delete', array('as' => 'books.delete', 'uses' => 'Admin\BooksController@destroy'));
        Route::get('{book}/confirm-delete', array('as' => 'books.confirm-delete', 'uses' => 'Admin\BooksController@getModalDelete'));
        Route::get('{book}/restore', array('as' => 'restore/book', 'uses' => 'Admin\BooksController@getRestore'));
        Route::get('{book}', array('as' => 'books.show', 'uses' => 'Admin\BooksController@show'));
        Route::post('{book}/passwordreset', array('as' => 'passwordreset', 'uses' => 'Admin\BooksController@passwordreset'));
    });
    Route::resource('books', 'Admin\BooksController');

    // Route::get('test', function() {
    //     return view('')
    // })
    Route::group(array('prefix' => 'news'), function () {
        Route::get('/', array('as' => 'news', 'uses' => 'Admin\NewsController@index'));
        Route::get('create', array('as' => 'news.create', 'uses' => 'Admin\NewsController@create'));
        Route::post('create', 'Admin\NewsController@store');
        // Route::get('{blog}/edit', array('as' => 'blog.edit', 'uses' => 'BlogController@edit'));
        // Route::post('{blog}/edit', 'BlogController@update');
        // Route::get('{blog}/delete', array('as' => 'blog.delete', 'uses' => 'BlogController@destroy'));
        // Route::get('{blog}/confirm-delete', array('as' => 'blog.confirm-delete', 'uses' => 'BlogController@getModalDelete'));
        // Route::get('{blog}/restore', array('as' => 'blog.restore', 'uses' => 'BlogController@restore'));
        // Route::get('{blog}/show', array('as' => 'blog.show', 'uses' => 'BlogController@show'));
        // Route::post('{blog}/storecomment', 'BlogController@storeComment');
    });
    Route::resource('news', 'Admin\NewsController');

});